# Generated by Django 2.0.5 on 2018-05-31 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='quiz',
        ),
    ]
