# Generated by Django 2.0.5 on 2018-05-31 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_remove_student_quiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_response',
            name='quiz_link',
        ),
        migrations.AddField(
            model_name='question',
            name='number_of_responses',
            field=models.IntegerField(default=0),
        ),
    ]
